language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
  - node_modules
install: yarn install
script:
  - yarn build
  - cp CNAME ./build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: build
  on:
    branch: master
branches:
  only:
    - master
    - /^greenkeeper/.*$/
